### ISSUE TITLE
Crossbar tests are failing since #227

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#246]
**Describe the bug**
Since the Mocha dependency bump from 9.2.2 to 10.2.0 (#227) my crossbar tests are failing

**To Reproduce**
1. `git checkout origin/dev`
2. `npm install`
3. `npm run test:crossbar`

**Expected behavior**
Crossbar tests should pass

**Current behavior**
```
1) Wampy.js with Crossbar
       Works with Json serializer:
     WebsocketError: Websocket error
      at Wampy._wsOnError (file:///home/mendonlu/wampy.js/src/wampy.js:1420:32)
      at W3CWebSocket._ws.onerror (file:///home/mendonlu/wampy.js/src/wampy.js:780:44)
      at W3CWebSocket._dispatchEvent [as dispatchEvent] (node_modules/yaeti/lib/EventTarget.js:107:17)
      at W3CWebSocket.onConnectFailed (node_modules/websocket/lib/W3CWebSocket.js:217:14)
      at WebSocketClient.<anonymous> (node_modules/websocket/lib/W3CWebSocket.js:59:25)
      at WebSocketClient.emit (node:events:513:28)
      at ClientRequest.handleRequestError (node_modules/websocket/lib/WebSocketClient.js:227:14)
      at ClientRequest.emit (node:events:513:28)
      at Socket.socketErrorListener (node:_http_client:481:9)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  2) Wampy.js with Crossbar
       works with Msgpack serialization:
     WebsocketError: Websocket error
      at Wampy._wsOnError (file:///home/mendonlu/wampy.js/src/wampy.js:1420:32)
      at W3CWebSocket._ws.onerror (file:///home/mendonlu/wampy.js/src/wampy.js:780:44)
      at W3CWebSocket._dispatchEvent [as dispatchEvent] (node_modules/yaeti/lib/EventTarget.js:107:17)
      at W3CWebSocket.onConnectFailed (node_modules/websocket/lib/W3CWebSocket.js:217:14)
      at WebSocketClient.<anonymous> (node_modules/websocket/lib/W3CWebSocket.js:59:25)
      at WebSocketClient.emit (node:events:513:28)
      at ClientRequest.handleRequestError (node_modules/websocket/lib/WebSocketClient.js:227:14)
      at ClientRequest.emit (node:events:513:28)
      at Socket.socketErrorListener (node:_http_client:481:9)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Node.js v16.17.1
 - Wampy.js v7.0.1
 - WAMP Router and version: idk

**Comment by KSDaemon** [comment]
Agrh... Well, we can simply revert back to mocha v9. Or someone should research and fix :)

**Comment by lucasrmendonca** [comment]
After inspecting [their release notes](https://github.com/mochajs/mocha/releases/tag/v10.0.0), I'm not sure what exactly made it stop working :(

Reverting back to 9.2.2 in the meantime
